send_command:
  target:
    entity:
      integration: rflink_ui
      domain: radio_frequency
  fields:
    protocol:
      required: true
      example: Unitec
      selector:
        text:
    command:
      required: true
      example: 1a4a;4;ON
      selector:
        text:

send_raw:
  target:
    entity:
      integration: rflink_ui
      domain: radio_frequency
  fields:
    packet:
      required: true
      example: 10;GPIOset;32;0;ON;
      selector:
        text:

simulate_packet:
  fields:
    packet:
      required: true
      example: 20;01;Kaku;ID=1234abcd;SWITCH=1;CMD=ON;
      selector:
        text:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: rflink_ui
